# Generated by Django 3.0 on 2019-12-08 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('cod_setor', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('matricula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=25)),
                ('senha', models.CharField(max_length=30)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='core.Setor')),
            ],
        ),
    ]
