# Generated by Django 3.0 on 2019-12-12 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chamado_tiposervico'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='tipoServico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='core.TipoServico'),
        ),
        migrations.AddField(
            model_name='tiposervico',
            name='prioridade',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAIXA', 'Baixa')], default='BAIXA', max_length=20),
        ),
    ]
