# Generated by Django 3.0 on 2019-12-12 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191211_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_resolucao', models.DateTimeField()),
                ('data_vinculo', models.DateTimeField()),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolvido', to='core.Chamado')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='core.Funcionario')),
            ],
        ),
    ]
