# Generated by Django 3.0 on 2019-12-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resolve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('chamado', models.ManyToManyField(related_name='produtos', to='core.Chamado')),
                ('produtos', models.ManyToManyField(related_name='produtos', to='core.Produto')),
            ],
        ),
    ]
